django/pythonwawum/accounts/urls.py
from __future__ import unicode_literals, absolute_import, print_function

from django.conf.urls import url

from .views import (
    ProfileCreateView, ProfileDetailView, ProfileListView, ProfileUpdateView,
    PositionListView,
)

urlpatterns = [
    url(r'^list/$', ProfileListView.as_view(), name='profile__list'),
    url(r'^position/list/$', PositionListView.as_view(), name='position__list'),
    url(r'^detail/(?P<pk>(\d+))/$', ProfileDetailView.as_view(), name='profile__detail'),
    url(r'^create/$', ProfileCreateView.as_view(), name='profile__create'),
    url(r'^edit/(?P<pk>(\d+))/$', ProfileUpdateView.as_view(), name='profile__edit'),
]

django/pythonwawum/ads/urls.py
from __future__ import unicode_literals, absolute_import, print_function

from django.conf.urls import url

from .views import current_datetime, ads_list, AdsList, AdCreateView


urlpatterns = [
    url(r'^date/', current_datetime, name='current_datetime'),
    url(r'^list/f/', ads_list, name='ads_list'),
    url(r'^list/', AdsList.as_view(), name='ads_list'),
    url(r'^create/', AdCreateView.as_view(), name='ads_create'),
]

django/pythonwawum/accounts/models.py
from __future__ import unicode_literals, absolute_import, print_function

from django.db import models
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from model_utils.models import TimeStampedModel
from django_extensions.db.fields import ShortUUIDField

from .enums import GenderEnum


class BaseModel(TimeStampedModel, models.Model):

    uuid = ShortUUIDField(_('uuid'), editable=False)

    class Meta:
        abstract = True


class Position(BaseModel):

    name = models.CharField(_('name'), max_length=256)

    class Meta:
        verbose_name = _('position')
        verbose_name_plural = _('positions')
        ordering = (
            'created',
        )

    def __unicode__(self):
        return "{name}".format(name=self.name)


class Profile(BaseModel):

    position = models.ForeignKey(Position, verbose_name=_('position'))
    gender = models.CharField(
        _('gender'), choices=GenderEnum.choices, max_length=1)

    class Meta:
        verbose_name = _('profile')
        verbose_name_plural = _('profiles')
        ordering = (
            'created',
        )

    def __unicode__(self):
        return "{position} {gender}".format(
            position=self.position.name, gender=self.gender,
        )

    def get_absolute_url(self):
        return reverse('profile__detail', kwargs=dict(pk=self.pk))

django/pythonwawum/accounts/forms.py
from __future__ import unicode_literals, absolute_import, print_function

from django import forms
from django.utils.translation import ugettext_lazy as _
from crispy_forms import layout, bootstrap
from crispy_forms.helper import FormHelper

from .enums import GenderEnum
from .models import Profile


class ProfileForm(forms.ModelForm):

    secret_password = forms.CharField(label=_('secret password'))

    class Meta:
        model = Profile
        fields = (
            'position',
            'gender',
            'secret_password',
        )

    def clean_secret_password(self):
        value = self.cleaned_data.get('secret_password')
        if value == 'show_errors':
            self.add_error('position', 'An error!')
            self.add_error('gender', 'Tadaaa')
            self.add_error('__all__', 'Tadaaa')
            raise forms.ValidationError('Invalid secret')
        return value

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields['position'].queryset = (
            self.fields['position'].queryset
            .exclude(name__startswith='K')
        )

    @property
    def helper(self):
        helper = FormHelper()
        helper.layout = layout.Layout(
            layout.Fieldset(
                _('Profile information'),
                'position',
                'gender',
                'secret_password',
            ),
            bootstrap.FormActions(
                layout.Submit('save', _('Save'), css_class="btn-primary"),
            ),
        )
        return helper

django/pythonwawum/accounts/views.py
from __future__ import unicode_literals, absolute_import, print_function

from django.views.generic import (
    CreateView, UpdateView, DetailView, ListView,
)
from .forms import ProfileForm
from .models import Profile, Position


class ProfileViewMixin(object):
    model = Profile
    form_class = ProfileForm


class ProfileCreateView(ProfileViewMixin, CreateView):
    pass


class ProfileUpdateView(ProfileViewMixin, UpdateView):
    pass


class ProfileDetailView(ProfileViewMixin, DetailView):
    pass


class ProfileListView(ProfileViewMixin, ListView):
    paginate_by = 5

    def get_queryset(self):
        return (
            super(ProfileListView, self)
            .get_queryset()
            .only('position', 'gender')
            .select_related('position')
        )


class PositionListView(ListView):
    model = Position

    def get_queryset(self):
        return (
            super(PositionListView, self)
            .get_queryset()
            # .only('position', 'gender')
            .prefetch_related('profile_set')
        )

django/pythonwawum/accounts/templates/accounts/position_list.html
{% extends 'base.html' %}

{% load crispy_forms_tags i18n %}

{% block content %}
  <div class="row">
    <div class="col-sm-12">
      <input value="" placeholder="Search..." />
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <table class="table table-condensed">
        <thead>
          <tr>
            <th>{% trans 'Position' %}</th>
            <th>{% trans 'Profiles' %}</th>
          </tr>
        </thead>
        <tbody>
          {% for position in object_list %}
            <tr>
              <td>{{ position.name }}</td>
              <td>
                {% for profile in position.profile_set.all %}
                  {{ profile.id }}{% if not forloop.last %},{% endif %}
                {% endfor %}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>

      <div class="pagination">
        <span class="step-links">
          {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
          {% endif %}

          <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
          </span>

          {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
          {% endif %}
        </span>
      </div>

    </div>
  </div>
{% endblock %}

django/pythonwawum/accounts/templates/accounts/profile_detail.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      {{ object }}
    </div>
  </div>
{% endblock %}

django/pythonwawum/accounts/templates/accounts/profile_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      {% crispy form %}
    </div>
  </div>
{% endblock %}

django/pythonwawum/accounts/templates/accounts/profile_list.html
{% extends 'base.html' %}

{% load crispy_forms_tags i18n %}

{% block content %}
  <div class="row">
    <div class="col-sm-12">
      <input value="" placeholder="Search..." />
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <table class="table table-condensed">
        <thead>
          <tr>
            <th></th>
            <th>{% trans 'Gender' %}</th>
            <th>{% trans 'Position' %}</th>
          </tr>
        </thead>
        <tbody>
          {% for profile in object_list %}
            <tr>
              <td><a href="{% url 'profile__edit' pk=profile.pk %}">Edit</a></td>
              <td>{{ profile.get_gender_display }}</td>
              <td>{{ profile.position.name }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>

      <div class="pagination">
        <span class="step-links">
          {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
          {% endif %}

          <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
          </span>

          {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
          {% endif %}
        </span>
      </div>

    </div>
  </div>
{% endblock %}